### ISSUE TITLE
signal for title_changed

### ISSUE THREAD

**Issue by killown** [ulinja/hyprpy#13]
I think hyprpy is lacking signal_active_window_title_changed, for example, firefox tab navigation or whatever app that uses tabs will change titles while the active window is the same

**Comment by ulinja** [comment]
Hi @killown, thank you for filing an issue, apologies for taking so long to reply.

Turns out Hyprland has been extended with a lot more events since last I checked, including the `windowtitle` event. I'll work on implementing these in hyprpy as soon as I can.

I've opened up a new issue (https://github.com/ulinja/hyprpy/issues/17) to track the progress on this update.
