### ISSUE TITLE
event activewindow is missing

### ISSUE THREAD

**Issue by Nama** [ulinja/hyprpy#14]
`activewindowv2` is currently used and `activewindow` would be nice to have, too.

Thank you very much.

**Comment by ulinja** [comment]
Hi @Nama, thank you for filing an issue. I had originally omitted `activewindow` from hyprpy, because `activewindowv2` does the trick for me:

```python
from hyprpy import Hyprland

instance = Hyprland()

def on_active_window_changed(sender, **kwargs):
    active_window_address = kwargs.get('active_window_address')
    active_window = instance.get_window_by_address(active_window_address)
    print(active_window.title)
    print(active_window.wm_class)

instance.signal_active_workspace_changed.connect(on_active_window_changed)
instance.watch()
```

I'm working on adding a whole bunch of other signals (https://github.com/ulinja/hyprpy/issues/17) anyways, so I'll add `activewindow` as well while I'm at it.

**Comment by Nama** [comment]
> because `activewindowv2` does the trick for me

yes, thats what im using currently, too. But `activewindow` would be a quicker way to just use the class instead of going with `active_window_address`.

> so I'll add `activewindow` as well while I'm at it.

perfect, thank you!
