### ISSUE TITLE
Slow `Hyprland` import

### ISSUE THREAD

**Issue by georgetian3** [ulinja/hyprpy#6]
Running `time` on a single line script `from hyprpy import Hyprland` takes ~0.1s on my laptop with an AMD 6800H CPU. However, calling further functions, such as `instance.get_window()` barely adds any time.  After commenting out some imports, it seems that Pydantic validation is what is taking the most time. 

My intended use case is to use this package to replace bash scripts that will be called quite often, e.g. providing data to [Eww polling variables](https://elkowar.github.io/eww/configuration.html#:~:text=Polling%20variables%20(defpoll)), so 0.1s somewhat slow. Therefore my questions are:

1. Is this the intended way for hyprpy to be used?
2. Would sacrificing data validation (or using something faster than Pydantic) be reasonable for a large increase in execution speeed?

**Comment by ulinja** [comment]
Hi @georgetian3,
python imports can be comparatively slow, especially when using extra libraries such as Pydantic. Pydantic's actual parsing speed is pretty fast, because it utilizes Rust under the hood.
I would not recommend importing Hyprpy every time you invoke a polling script. In fact, one of Hyprpy's main features is being able to avoid polling, by [using signals](https://hyprpy.lobbes.dev/hyprpy.components.html#reacting-to-events) in conjunction with `Instance.watch()`. You can define a callback function which updates your eww variable whenever the event you are interested in occurs:

```python
from hyprpy import Hyprland
from hyprpy.utils import shell

instance = Hyprland()

def your_callback(sender, **kwargs):
    workspace = kwargs.get("active_workspace")
    shell.run_or_fail(["eww", "update", f"myEwwVar={active_workspace.id}"])

instance.signal_active_workspace_changed.connect(your_callback)
instance.watch()
```
This script updates a dynamic eww variable called `myEwwVar` to contain the active workspace number, by invoking the shell command `eww update`, as soon as the workspace changes. The `watch()` method is very efficient, because it does not poll the socket. Instead, it relies on the kernel to notify python as soon as event data is ready. It is much more efficient than polling, and reacts faster as well.
